### ISSUE TITLE
Exchange page table doesn't work

### ISSUE THREAD

**Issue by kascheri12** [rotkehlchenio/rotkehlchen#187] opened 2018-10-06 16:59 UTC
## Problem Definition

After selecting View Details for an exchange, the table does not work with more than 10 rows.

Nothing happens when I change the number of entries and nothing happens when I click Next or 2.

<img width="1238" alt="screen shot 2018-10-06 at 9 54 55 am" src="https://user-images.githubusercontent.com/4165385/46573730-45c57280-c94e-11e8-9977-d72c151e6fa8.png">

**Comment by LefterisJP** [comment] 2018-10-06 17:27
Hmm so the first 10 entries work? And if you change the page it does not work?

**Comment by kascheri12** [comment] 2018-10-06 17:29
Correct, I have my entries hidden but they do show up. The initial table loads as I would expect. It's just that nothing happens when I click the paging buttons or change the drop down for entries. There is no errors in the console.

**Comment by LefterisJP** [comment] 2018-10-07 08:04
@kascheri12 I can confirm this. Note to self and to @kelsos for the UI tests, to also test page changing in most tables.

**Comment by LefterisJP** [comment] 2018-10-07 08:08
@kascheri12 But just to confirm. The first 10 rows appear. Once you change the page, nothing happens. Right?

**Comment by LefterisJP** [comment] 2018-10-07 08:12
Hah! This is actually a duplicate of: https://github.com/rotkehlchenio/rotkehlchen/issues/4

It happens in a non-deterministic way. Some times it works, some times it does not and there is nothing in the logs. So this is not something new that was introduced via typescript changes.

**Closed** 2018-10-07 12:44 UTC
Labels: bug
