### ISSUE TITLE
Startup Error - they Python backend crushed

### ISSUE THREAD

**Issue by chickenlasers** [rotkehlchenio/rotkehlchen#339] opened 2019-04-12 17:36 UTC
## Problem Definition

I get the following error when I run rotkehlchen using the darwin-x64 package:

https://pbs.twimg.com/media/D3-BXC2WsAAeEaz.png

Rotkehlchen also logs debug information to the `rotkehlchen.log` file. Please attach it to the
issue as it may help us find the source of the issue faster.

I couldnt find any log file in the folder, so I must be doing something wrong.

### System Description

Tried running the script but it didnt do anything except for the first line:

Darwin XXXs-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64 x86_64

Im using MacOS Sierra 10.12.6.

Sorry if this wasnt a useful issue request, I'm not a dev and have never done one of these..!

**Comment by chickenlasers** [comment] 2019-04-12 17:40
I tried running that unix executable and got this in the terminal window:

XXXs-MacBook-Pro:~ xxx$ /Users/XXX/Desktop/rotkehlchen-darwin-x64/rotkehlchen ; exit;
child process success on port 4242
CREATED PYPROCESS
python subprocess killed with signal null and code 255

**Comment by LefterisJP** [comment] 2019-04-12 21:24
Hello @chickenlasers!

Thank you for trying Rotkehlchen even though it's still before v1.0.

So I assume you downloaded the latest release? (v0.6.0) from [here](https://github.com/rotkehlchenio/rotkehlchen/releases/tag/v0.6.0) ?

Did you navigate via the command line to the directory where you downloaded it? Seems to be `/Users/XXX/Desktop/rotkehlchen-darwin-x64` from what you posted.

Once there type `./rotkehlchen` and tell me if it works from inside that directory. Also the logs should be in that same directory.

**Comment by chickenlasers** [comment] 2019-04-12 23:17
Hi, thanks for the fast reply!

Yes, I download the latest release from that link.

I tried navigating to that folder in the command line, ran that command but still got the same error. Interestingly the logs are also still nowhere to be found.

**Comment by LefterisJP** [comment] 2019-04-13 08:05
So by doing `ls` in the folder you don't see `rotkehlchen.log` file in there I guess? I just tried it in an OSX machine and it works fine for me. Perhaps I am am making some assumptions about OSX that my system has and other systems don't have by default (I normally work on Linux).

@ulope You had tried Rotkehlchen in OSX in the past. Can you maybe try to see if you can help here? Any idea what could be wrong? Can you see if the release works for you?

**Comment by chickenlasers** [comment] 2019-04-13 16:35
Yeah I tried the ls command and it still did not show. 

I guess its a hard thing to pin point, especially when you aren't particularly familiar with the OS.

**Comment by pavelvolek** [comment] 2019-05-06 17:42
@chickenlasers any luck figuring this up? Same problem here..

**Comment by ulope** [comment] 2019-05-07 17:24
I just tested the latest release, works normally on macOS 10.14.4.

@chickenlasers You wrote you're using 10.12. It's not unlikely that this is the problem.

**Comment by debris** [comment] 2019-06-25 08:46
I reproduced the same problem with the latest release (`0.6`). macOS 10.14.3

<img width="488" alt="Screenshot 2019-06-25 at 16 44 34" src="https://user-images.githubusercontent.com/2613714/60083652-b294cd00-9768-11e9-8edc-77d032fffead.png">
<img width="912" alt="Screenshot 2019-06-25 at 16 44 40" src="https://user-images.githubusercontent.com/2613714/60083668-b9bbdb00-9768-11e9-97c8-da6d08a12969.png">

**Comment by LefterisJP** [comment] 2019-06-25 14:38
Hey @debris !!

So can you tell me how did you try to run rotkehlchen? Did you download the latest version, try to run the executable from the terminal?

**Comment by debris** [comment] 2019-06-26 05:51
I downloaded the latest executable, unziped, opened directory in Finder, then right clicked -> Open

**Comment by LefterisJP** [comment] 2019-06-26 06:37
can you try executing from the terminal? I know it's not the OSX way, but I am also not very adept at OSX. Hopefully it will get better by v1.0.

**Comment by LefterisJP** [comment] 2019-07-24 21:21
So guys as far as this issue is concerned, all users who reported this issue in the past seemed to have not followed the guide correctly. I will close it in favour of: https://github.com/rotkehlchenio/rotkehlchen/issues/426

Note the addition in the docs [here](https://rotkehlchen.readthedocs.io/en/latest/installation_guide.html#osx).

Even got a screenshot with the file you must click: 
![osx_which_executable](https://user-images.githubusercontent.com/1658405/61829260-cebf8300-ae68-11e9-8d7b-891a9370f127.png)


Will also hopefully [switch to a DMG](https://github.com/rotkehlchenio/rotkehlchen/issues/26) at some point.

**Closed by LefterisJP** 2019-07-24 21:21 UTC
