### ISSUE TITLE
Reference before assignment

### ISSUE THREAD

**Issue by rakanalh** [rotkehlchenio/rotkehlchen#308] opened 2019-02-26 19:51 UTC
## Problem Definition

Seems like when updating to the latest master, somehow generating a report started throwing this exception:
```
26/02/2019 20:46:15 CET -- ERROR:rotkehlchen.server:Greenlet for task 6 dies with exception: local variable 'history_json_data' referenced before assignment.
Exception Name: <class 'UnboundLocalError'>
Exception Info: local variable 'history_json_data' referenced before assignment
Traceback:
   File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/rakan/Code/Python/rotkehlchen/rotkehlchen/server.py", line 115, in _query_async
    result = getattr(self, command)(**kwargs)
  File "/home/rakan/Code/Python/rotkehlchen/rotkehlchen/server.py", line 230, in process_trade_history
    result, error_or_empty = self.rotkehlchen.process_history(start_ts, end_ts)
  File "/home/rakan/Code/Python/rotkehlchen/rotkehlchen/rotkehlchen.py", line 482, in process_history
    end_at_least_ts=end_ts,
  File "/home/rakan/Code/Python/rotkehlchen/rotkehlchen/history.py", line 817, in get_history
    all_history_okay = data_up_todate(history_json_data, start_ts, end_at_least_ts)
```

Probably because my `trades_history.json` file did not contain proper JSON (another issue).

**Comment by LefterisJP** [comment] 2019-07-24 21:45
@rakanalh can this issue be reproduced with latest master?

**Comment by LefterisJP** [comment] 2019-08-31 07:47
Since this is not reproducible I am closing the issue. If you can somehow tell me how to reproduce it with latest master please re-open or make another issue.

**Closed by LefterisJP** 2019-08-31 07:47 UTC
