### ISSUE TITLE
Utilize Cryptocompare historical price API v2

### ISSUE THREAD

**Issue by LefterisJP** [rotkehlchenio/rotkehlchen#505] opened 2019-09-13 10:46 UTC
## Problem Definition

Current cryptocompare v1 historical price API has had problems of incosistent historical data. See https://github.com/rotkehlchenio/rotkehlchen/issues/377

To solve that problem cryptocompare has has a revamp of that API and introduced a [new version](https://blog.cryptocompare.com/historical-data-api-update-4ee44c549a8f)

## Task

Utilize v2 of cryptocompare historical price API.

Should also fix #377 

The task basically consists of switching to v2 of the API and slightly adjusting the response processing to that the response can be processed.

For v1 it was response -> Data, and with v2 it should be response -> Data -> Data.

In addition after this is implemented the expected values for the following tests should be adjusted and the tests be unskipped:

- https://github.com/rotkehlchenio/rotkehlchen/blob/fe9639c5eaa5d83d0efc3e2c272fdd0e4ec194ea/rotkehlchen/tests/test_cryptocompare.py#L59

- https://github.com/rotkehlchenio/rotkehlchen/blob/fe9639c5eaa5d83d0efc3e2c272fdd0e4ec194ea/rotkehlchen/tests/test_price_history.py#L11

- https://github.com/rotkehlchenio/rotkehlchen/blob/fe9639c5eaa5d83d0efc3e2c272fdd0e4ec194ea/rotkehlchen/tests/test_price_history.py#L52

**Comment by AndrewBezold** [comment] 2019-10-01 02:32
Working on this, should have a pull request within a couple days hopefully.  Seems pretty straightforward.  For test_cryptocompare.py, do you want that unskipped?  It claims to be skipped as a duplicate of another test, but that other test doesn't seem to exist.  Also, you have some documentation in the comments about the v1 issue, do you want that kept and added to, or removed?

**Comment by LefterisJP** [comment] 2019-10-01 07:26
Hey @AndrewBezold thanks!

> For test_cryptocompare.py, do you want that unskipped? It claims to be skipped as a duplicate of another test, but that other test doesn't seem to exist

It does exist here:

https://github.com/rotkehlchenio/rotkehlchen/blob/1dea30e4578803939bd13ee240349d227fbdee18/rotkehlchen/tests/test_end_to_end_tax_report.py#L581

> Also, you have some documentation in the comments about the v1 issue, do you want that kept and added to, or removed?

I guess removed if we switch to v2.


Also regarding the unskipped tests I believe it was these ones that need to be unskipped when switching to v2: https://github.com/rotkehlchenio/rotkehlchen/blob/1dea30e4578803939bd13ee240349d227fbdee18/rotkehlchen/tests/test_price_history.py#L11

And for which the new numbers (whatever they may be) used.

**Comment by LefterisJP** [comment] 2019-10-02 16:02
Hey @AndrewBezold question. Would it be possile to have this done by Friday? If this and 2 other issues are done perhaps a release can be made before my flying to Devcon.

**Comment by AndrewBezold** [comment] 2019-10-02 21:45
Yes, that should be doable.  I've got most of it finished, just working on fixing the last test.

**Closed** 2019-10-04 15:04 UTC
Labels: Affects P/L Calculation, good first issue
