### ISSUE TITLE
Querying error Kraken

### ISSUE THREAD

**Issue by Phistr90** [rotkehlchenio/rotkehlchen#71] opened 2018-05-31 12:16 UTC
31/05/2018 14:13:21 CEST -- DEBUG:rotkehlchen.rotkehlchen:Main loop start
31/05/2018 14:13:21 CEST -- DEBUG:rotkehlchen.rotkehlchen:Maybe upload to server
31/05/2018 14:13:21 CEST -- DEBUG:rotkehlchen.rotkehlchen:Main loop end
31/05/2018 14:13:31 CEST -- WARNING:rotkehlchen.ethchain:Could not connect to a local ethereum node. Will use etherscan only
31/05/2018 14:13:31 CEST -- DEBUG:rotkehlchen.server:NEW TASK query_exchange_balances (kwargs:{'name': 'kraken'}) with ID: 0
31/05/2018 14:13:31 CEST -- DEBUG:rotkehlchen.server:NEW TASK query_blockchain_balances (kwargs:{}) with ID: 1
31/05/2018 14:13:32 CEST -- DEBUG:rotkehlchen.server:Querying task result with task id 0
31/05/2018 14:13:32 CEST -- DEBUG:rotkehlchen.server:Querying task result with task id 1
31/05/2018 14:13:32 CEST -- DEBUG:rotkehlchen.server:Found response for task 1
31/05/2018 14:13:34 CEST -- DEBUG:rotkehlchen.server:Querying task result with task id 0
31/05/2018 14:13:36 CEST -- DEBUG:rotkehlchen.server:Querying task result with task id 0
31/05/2018 14:13:38 CEST -- DEBUG:rotkehlchen.server:Querying task result with task id 0
31/05/2018 14:13:40 CEST -- DEBUG:rotkehlchen.server:Querying task result with task id 0
31/05/2018 14:13:41 CEST -- ERROR:rotkehlchen.server:Greenlet for task 0 dies with exception: 'ZUSD'.
Exception Name: <class 'KeyError'>
Exception Info: 'ZUSD'
Traceback:
   File "/home/philipp/rotkehlchen/rotkehlchen/rotkehlchen/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/philipp/rotkehlchen/rotkehlchen/rotkehlchen/server.py", line 93, in _query_async
    result = getattr(self, command)(**kwargs)
  File "/home/philipp/rotkehlchen/rotkehlchen/rotkehlchen/server.py", line 161, in query_exchange_balances
    balances = getattr(self.rotkehlchen, name).query_balances()
  File "/home/philipp/rotkehlchen/rotkehlchen/rotkehlchen/utils.py", line 85, in wrapper
    result = f(wrappingobj, *args)
  File "/home/philipp/rotkehlchen/rotkehlchen/rotkehlchen/kraken.py", line 275, in query_balances
    common_name = KRAKEN_TO_WORLD[k]

31/05/2018 14:13:42 CEST -- DEBUG:rotkehlchen.server:Querying task result with task id 0
31/05/2018 14:13:42 CEST -- DEBUG:rotkehlchen.server:Found response for task 0

**Comment by LefterisJP** [comment] 2018-05-31 14:17
Hello @Phistr90. This is a duplicate of issue #68 and should have just been fixed in latest master.

**Comment by LefterisJP** [comment] 2018-05-31 14:30
@Phistr90 if this is not fixed for you in latest master please tell me so by reopening the issue

**Closed** 2018-05-31 14:30 UTC
