### ISSUE TITLE
crash my computer . 

### ISSUE THREAD

**Issue by xiaomingfuckeasylife** [rotkehlchenio/rotkehlchen#88] opened 2018-06-24 06:58 UTC
when i install the darwin package. it verified a long time without any progress . so i clicked to stop .then my computer froze . had to restart the computer .  

- is the software take a huge amount of memory that makes the computer crash?

**Comment by LefterisJP** [comment] 2018-06-24 08:19
Hmm no that naturally should not happen. What are the specs of your computer?

**Comment by xiaomingfuckeasylife** [comment] 2018-06-24 11:51
```
MacBook Air (13-inch, Early 2015)
1.6 GHz Intel Core i5
4 GB 1600 MHz DDR3
Intel HD Graphics 6000 1536 MB
```

**Comment by LefterisJP** [comment] 2018-06-24 12:09
And what OSX Version?

>when i install the darwin package. it verified a long time without any progress .

There is no OSX (or linux package) yet.

It's just a compiled binary inside a zip archive. You should be able to download it, unzip and then run th executable as per the simple guide shown [here](https://github.com/rotkehlchenio/rotkehlchen#osx).

**Comment by xiaomingfuckeasylife** [comment] 2018-06-25 03:44
ok .cool . may be because my computer is just too old 
- OSX EI capitan 10.11.6 (15G31)

**Comment by LefterisJP** [comment] 2018-07-08 08:07
Tested it in different machines and the Macos executable runs fine. I can not reproduce this issue and since there is not enough information to debug it I will close it.

**Closed by LefterisJP** 2018-07-08 08:07 UTC
