### ISSUE TITLE
copy/past does not work under macOS

### ISSUE THREAD

**Issue by koeppelmann** [rotkehlchenio/rotkehlchen#349] opened 2019-05-18 22:27 UTC
## Problem Definition

I can't use copy/paste which makes it basically impossible to add my Ethereum addresses.
Neither CMD/V nor ctr/V works.

### System Description

MacOS 10.14.4
Rotkelchen: precompiled: v3.0.12

**Comment by LefterisJP** [comment] 2019-05-18 22:34
Okay that's weird. I will have to look into this. Will take me some time to dust off my old macbook.

**Comment by LefterisJP** [comment] 2019-05-19 19:44
Okay so @koeppelmann it seems that Electron and OSX need special care to actually enable copy paste.

- [Reference 1](https://pracucci.com/atom-electron-enable-copy-and-paste.html)
- [Reference 2](https://www.codedmaster.com/2017/01/24/getting-electron-copy-paste-shortcuts-for-mac-builds/)

I tested with the last release of rotkehlchen on OSX (v0.6.0). Did you also test the same version @koeppelmann ?
And I can confirm this happens there.

But with latest master this does not happpen. And I am not sure why. But by adding this [patch](https://github.com/rotkehlchenio/rotkehlchen/pull/352/files#diff-7a9076d6d94e62c13d641aa71f19ae8e) to main.js of the `v0.6.0` release copy paste works for that release.

If you want to do that @koeppelmann, assuming you start from the unzipped rotkehlchen directory you will find the file here:

`rotkehlchen-darwin-x64/rotkehlchen.app/Contents/Resourses/app/main.js`

You can edit it manually and add the patch I showed above. Should go in the same function (code has changed in master since `v0.6.0`). Then copy paste will work.

But @kelsos I need your help here a bit. Why does it work anyway on latest master? Is it something that only happens on release builds of Electron in OSX? Or what? The only change I could find is your inspection menu since v0.6.0 but even removing that in an OSX machine I could still use copy paste. Any ideas?

**Comment by kelsos** [comment] 2019-05-19 19:55
@LefterisJP the latest master that it works for is it a packaged version or a development one?
Maybe something gets added automatically when the environment is not production.

**Comment by LefterisJP** [comment] 2019-05-19 20:11
@kelsos its a simple `npm start` from master

**Comment by kelsos** [comment] 2019-05-20 07:51
I am a little bit curious. What if you go and remove the whole edit menu for the development version? Would the copy paste still work? One of the differences between development and production is that the menus were completely removed. Maybe electron on OSX relies on the edit menu being present to enable the copy/paste functionality.

**Comment by LefterisJP** [comment] 2019-05-20 08:36
I did that yesterday and it still worked when doing `npm` start @kelsos. Also thought the right click menu you added had something to do with it.

**Comment by LefterisJP** [comment] 2019-05-20 09:42
Should be fixed by https://github.com/rotkehlchenio/rotkehlchen/pull/352 but have to check with next release to be 100% sure.

**Closed** 2019-05-20 09:41 UTC
